### PR TITLE
Wear os support

### LINKED ISSUE #10: Wear OS by Google Support
It would be nice if the Evil Insult Generator could work on smartwatches too. 😈

### PR DESCRIPTION
**Pull request by Biren-Nayak**
Closes #10 

- Created a qualifier layout for awtch and added required dependencies in Manifest.xml to support wear OS.

- Added Tooltip text in share and generate buttons.

- Modified Toolbar to support round screens

<table width="200">
<tr align="center"> 
<td> 
Result
</td>
</tr>
<tr>
<td>

</td>
</tr>
</table>

### CODE REVIEW

**Comment by EvilInsultGenerator** [comment]
Thank you so much for your contribution! 😘

**Comment by EvilInsultGenerator** [comment]
Hey @Biren-Nayak,
may you please create a folder `wearScreenshots` under `fastlane/metadata/android/en-US/images` and add three screenshots of Evil Insult Generator running on Wear OS?

**Comment by Biren-Nayak** [comment]
> Hey @Biren-Nayak, may you please create a folder `wearScreenshots` under `fastlane/metadata/android/en-US/images` and add three screenshots of Evil Insult Generator running on Wear OS?

@EvilInsultGenerator  Can I upload a screenshot on a gdrive link here?

**Comment by EvilInsultGenerator** [comment]
> > Hey @Biren-Nayak, may you please create a folder `wearScreenshots` under `fastlane/metadata/android/en-US/images` and add three screenshots of Evil Insult Generator running on Wear OS?
> 
> @EvilInsultGenerator Can I upload a screenshot on a gdrive link here?

Yes, you may put a gdrive link here, @Biren-Nayak.

**Comment by Mhommab** [comment]
تم الإرسال من هاتف HONOR الخاص بي-------- الرسالة الأصلية --------من:‏ Biren ***@***.***>التاريخ:‏ الخميس، 25 أغسطس، 2022 5:42 مإلى:‏ EvilInsultGenerator/android-app ***@***.***>نسخة إلى:‏ Subscribed ***@***.***>الموضوع:‏ Re: [EvilInsultGenerator/android-app] Wear os support (PR #35)

Hey @Biren-Nayak, may you please create a folder wearScreenshots under fastlane/metadata/android/en-US/images and add three screenshots of Evil Insult Generator running on Wear OS?

@EvilInsultGenerator  Can I upload a screenshot on a gdrive link here?

**Comment by Biren-Nayak** [comment]
@EvilInsultGenerator Here is the folder drive link
https://drive.google.com/drive/folders/16LZIyb7sIur55VH5DgmVa9jEfh9LYv_0?usp=sharing

**Comment by EvilInsultGenerator** [comment]
> @EvilInsultGenerator Here is the folder drive link https://drive.google.com/drive/folders/16LZIyb7sIur55VH5DgmVa9jEfh9LYv_0?usp=sharing

Thanks! 👍

**Pull request merged**
