### PR TITLE
Added Indonesian Translations

### PR DESCRIPTION
**Pull request by QuartzAl**
Please tell me if I needed to do anything extra, my first time doing a pull request

### CODE REVIEW

**Comment by EvilInsultGenerator** [comment]
Congratulations @QuartzAl! This looks awesome! Thank you so much for your support! 😘

**Comment by EvilInsultGenerator** [comment]
Can you please put the translation on [Crowdin](https://crowdin.com/project/evil-insult-generator-android/id#) too, @QuartzAl? Thanks!

**Comment by QuartzAl** [comment]
do I just start translating those strings? @EvilInsultGenerator ?
(If so I just did it)
I never heard of Crowdin before, just recently made an account

**Comment by EvilInsultGenerator** [comment]
Yes, your translation of the strings was succesfull. 👍
Please translate the `google_play.xml` on Crowdin too. It is basically the same like the `full_description.txt `here on GitHub. You can just copy & paste. The advantage of Crowdin is that it has an integration for Google Play.

**Comment by QuartzAl** [comment]
oh ok, I'll get to it too

**Pull request merged**
