### PR TITLE
Dev: Add French translation

### PR DESCRIPTION
**Pull request by yoobi**

### CODE REVIEW

**Comment by yoobi** [comment]
I've also translate the google_play file but I don't where to put in the project so here it is in attachment

[google_play.xml.zip](https://github.com/EvilInsultGenerator/android-app/files/5307725/google_play.xml.zip)

**Comment by EvilInsultGenerator** [comment]
The description for the app stores goes into `fastlane/metadata/android/fr-FR`. You can copy the `en-US` folder and just change the `full_description.txt` and `short_description.txt`.

**Comment by yoobi** [comment]
Okay thanks :) I've added it

**Comment by EvilInsultGenerator** [comment]
Perfect, thank you so much for your support @yoobi! 😘

**Comment by yoobi** [comment]
Hello, Hacktoberfest rules has changed could you add the label `hacktoberfest-accepted` on the PR ? thanks :)

**Comment by EvilInsultGenerator** [comment]
Doesn't this PR show up in your Hacktoberfest dashboard?

**Comment by yoobi** [comment]
Yep you're right, my bad :)

**Pull request merged**
