### PR TITLE
Added Portuguese translation

### PR DESCRIPTION
**Pull request by larissayasin**
added brazilian portuguese translation.

### CODE REVIEW

**Comment by larissayasin** [comment]
I just saw there is a PR with the crowdin translations (I imported the string file from there too so it is the same). 
I can remove the strings file to avoid any conflicts.

**Comment by EvilInsultGenerator** [comment]
Awesome, thank you so much for your help @larissayasin! 😘

**Comment by EvilInsultGenerator** [comment]
Can you please translate the `google_play.xml` on Crowdin too, @larissayasin? It is basically just putting the stuff from the `full_description.txt` on there. Thanks!

**Comment by larissayasin** [comment]
@EvilInsultGenerator Done!

**Pull request merged**
